name: bulk-rnaseq-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - fastqc
  - multiqc
  - trim-galore
  - cutadapt
  - bowtie2
  - samtools
  - subread  # featureCounts
  - r-base=4.3
  - r-ggplot2
  - r-pheatmap
  - bioconductor-edger
  - bioconductor-limma
